export const flightCodes = {
    "Alesund, Norway"  : "AES",
    "Alexander Bay - Kortdoorn, South Africa"  : "ALJ",
    "Alexandria - Borg el Arab Airport, Egypt"  : "HBH",
    "Alexandria - El Nhouza Airport, Egypt"  : "ALY",
    "Alexandria - Esler Field, USA (LA)"  : "ESF",
    "Alfujairah (Fujairah), United Arab Emirates"  : "FJR",
    "Alghero Sassari, Italy"  : "AHO",
    "Algiers, Houari Boumediene Airport, Algeria"  : "ALG",
    "Al Hoceima, Morocco"  : "AHU",
    "Alicante, Spain"  : "ALC",
    "Alice Springs, Australia"  : "ASP",
    "Alldays, South Africa"  : "ADY",
    "Allentown (PA), USA"  : "ABE",
    "Almaty (Alma Ata) - Almaty International Airport, Kazakhstan"  : "ALA",
    "Almeria, Spain"  : "LEI",
    "Alta, Norway"  : "ALF",
    "Altay, PR China"  : "AAT",
    "Altenrhein, Switzerland"  : "ACH",
    "Altoona (PA), USA"  : "AOO",
    "Altus, USA"  : "AXS",
    "Amami, Japan"  : "ASJ",
    "Amarillo (TX), USA"  : "AMA",
    "Amazon Bay, Papua New Guinea"  : "AZB",
    "Amman - Queen Alia International Airport, Jordan"  : "AMM",
    "Amman - Amman-Marka International Airport, Jordan"  : "ADJ",
    "Amritsar, India"  : "ATQ",
    "Amsterdam - Amsterdam Airport Schiphol, Netherlands"  : "AMS",
    "Anand, India"  : "QNB",
    "Anchorage (AK) - Ted Stevens Anchorage International, USA"  : "ANC",
    "Ancona - Ancona Falconara Airport, Italy"  : "AOI",
    "Andorra La Vella - Heliport, Andorra"  : "ALV",
    "Anguilla, Anguilla"  : "AXA",
    "Anjouan - Anjouan Airport, Comoros (Comores)"  : "AJN",
    "Ankara, Turkey"  : "ANK",
    "Ankara - Esenboğa International Airport, Turkey"  : "ESB",
    "Annaba, Algeria"  : "AAE",
    "Ann Arbor (MI), USA"  : "ARB",
    "Annecy, France"  : "NCY",
    "Anniston (AL), USA"  : "ANB",
    "Antalya, Turkey"  : "AYT",
    "Antananarivo (Tanannarive) - Ivato International Airport, Madagascar"  : "TNR",
    "Antigua, V.C. Bird International, Antigua and Barbuda"  : "ANU",
    "Antwerp, Belgium"  : "ANR",
    "Aomori, Japan"  : "AOJ",
    "Apia - Faleolo International Airport, Samoa"  : "APW",
    "Appelton/Neenah/Menasha (WI), USA"  : "ATW",
    "Aqaba, Jordan"  : "AQJ",
    "Aracaju, Brazil"  : "AJU",
    "Arkhangelsk, Russia"  : "ARH",
    "Arusha, Tanzania"  : "ARK",
    "Araxos, Greece"  : "GPA",
    "Arlit, Niger"  : "RLT",
    "Arrecife/Lanzarote, Spain"  : "ACE",
    "Aruba - Reina Beatrix International, Oranjestad, Aruba"  : "AUA",
    "Asheville (NC), USA"  : "AVL",
    "Ashgabat - Saparmurat Turkmenbashy Int. Airport, Turkmenistan"  : "ASB",
    "Asmara - Asmara International, Eritrea"  : "ASM",
    "Aspen, (CO) - Aspen-Pitkin County Airport, USA"  : "ASE",
    "Assiut, Egypt"  : "ATZ",
    "Astana - Astana International Airport, Kazakhstan"  : "TSE",
    "Asuncion - Asunción International Airport, Paraguay"  : "ASU",
    "Aswan - Daraw Airport, Egypt"  : "ASW",
    "Athens - Elefthérios Venizélos International Airport, Greece"  : "ATH",
    "Athens, Hellinikon Airport, Greece"  : "HEW",
    "Athens (GA), USA"  : "AHN",
    "Athens (OH), USA"  : "ATO",
    "Atlanta (GA) - Hartsfield Atlanta International Airport, USA"  : "ATL",
    "Atlantic City (NJ) - Atlantic City International, USA"  : "ACY",
    "Attawapiskat, NT, Canada"  : "YAT",
    "Auckland - Auckland International Airport, New Zealand"  : "AKL",
    "Augsburg - Augsbur gAirport, Germany"  : "AGB",
    "Augusta (GA), USA"  : "AGS",
    "Augusta (ME) - Augusta State Airport, USA"  : "AUG",
    "Aurillac, France"  : "AUR",
    "Austin (TX) - Austin-Bergstrom Airport, USA"  : "AUS",
    "Ayawasi, Indonesia"  : "AYW",
    "Ayers Rock - Connellan, Australia"  : "AYQ",
    "Ayr, Australia"  : "AYR",
    "Badajoz, Spain"  : "BJZ",
    "Bagdad - Baghdad International Airport, Iraq"  : "BGW",
    "Bagdogra, India"  : "IXB",
    "Bahamas - Lynden Pindling International Airport, The Bahamas"  : "NAS",
    "Bahawalpur, Pakistan"  : "BHV",
    "Bahrain - Bahrain International Airport, Bahrain"  : "BAH",
    "Bakersfield (CA), USA"  : "BFL",
    "Baku - Heydar Aliyev International Airport, Azerbaijan"  : "BAK",
    "Ballina, Australia"  : "BNK",
    "Baltimore (MD) - Washington International Airport, USA"  : "BWI",
    "Bamaga, Australia"  : "ABM",
    "Bamako - Bamako-Sénou International Airport, Mali"  : "BKO",
    "Bambari, Central African Republic"  : "BBY",
    "Bandar Seri Begawan - Brunei International Airport, Brunei"  : "BWN",
    "Bandung - Husein Sastranegara International Airport, Indonesia"  : "BDO",
    "Bangalore, India"  : "BLR",
    "Bangassou, Central African Republic"  : "BGU",
    "Bangkok, Don Muang, Thailand"  : "DMK",
    "Bangkok, Suvarnabhumi International, Thailand"  : "BKK",
    "Bangor (ME), USA"  : "BGR",
    "Bangui - M'Poko International Airport, Central African Republic"  : "BGF",
    "Banjul - Banjul International Airport (Yundum International), Gambia"  : "BJL",
    "Bannu, Pakistan"  : "BNP",
    "Barcelona, Spain"  : "BCN",
    "Barcelona, Venezuela"  : "BLA",
    "Bardufoss, Norway"  : "BDU",
    "Bari, Italy"  : "BRI",
    "Barisal, Bangladesh"  : "BZL",
    "Baroda, India"  : "BDQ",
    "Barra (the famous tidal beach landing), United Kingdom"  : "BRR",
    "Barranquilla, Colombia"  : "BAQ",
    "Basel, Switzerland"  : "BSL",
    "Basel/Mulhouse, Switzerland/France"  : "EAP",
    "Basra, Basrah, Iraq"  : "BSR",
    "Basse-Terre - Pointe-à-Pitre International Airport, Guadeloupe"  : "PTP",
    "Basseterre - Robert L. Bradshaw International Airport, Saint Kitts and Nevis"  : "SKB",
    "Bastia, France"  : "BIA",
    "Baton Rouge (LA) - Baton Rouge Metropolitan Airport, USA"  : "BTR",
    "Bayreuth - Bindlacher-Berg, Germany"  : "BYU",
    "Beaumont/Pt. Arthur (TX), USA"  : "BPT",
    "Beckley (WV), USA"  : "BKW",
    "Beef Island - Terrance B. Lettsome, Virgin Islands (British)"  : "EIS",
    "Beijing, China"  : "PEK",
    "Beijing - Nanyuan Airport, China"  : "NAY",
    "Beira, Mozambique"  : "BEW",
    "Beirut - Beirut Rafic Hariri International Airport, Lebanon"  : "BEY",
    "Belem - Val de Cans International Airport, Brazil"  : "BEL",
    "Belfast - George Best Belfast City Airport, United Kingdom"  : "BHD",
    "Belfast - Belfast International Airport, United Kingdom"  : "BFS",
    "Belgaum, India"  : "IXG",
    "Belgrad (Beograd) - Belgrade Nikola Tesla International, Serbia"  : "BEG",
    "Belize City - Philip S.W.Goldson International, Belize"  : "BZE",
    "Bellingham (WA), USA"  : "BLI",
    "Belo Horizonte - Tancredo Neves International Airport, Brazil"  : "CNF",
    "Bemidji (MN), USA"  : "BJI",
    "Benbecula, United Kingdom"  : "BEB",
    "Benghazi (Bengasi), Libya"  : "BEN",
    "Benguela, Angola"  : "BUG",
    "Benton Harbour (MI), USA"  : "BEH",
    "Berberati, Central African Republic"  : "BBT",
    "Bergamo/Milan - Orio Al Serio, Italy"  : "BGY",
    "Bergen, Norway"  : "BGO",
    "Bergerac - Roumanieres, France"  : "EGC",
    "Berlin, Germany"  : "BER",
    "Berlin, Schoenefeld, Germany"  : "SXF",
    "Berlin, Tegel, Germany"  : "TXL",
    "Berlin, Tempelhof (ceased operating in 2008), Germany"  : "THF",
    "Bermuda - L.F. Wade International Airport, Bermuda"  : "BDA",
    "Berne, Bern-Belp, Switzerland"  : "BRN",
    "Berne, Railway Service, Switzerland"  : "ZDJ",
    "Bethel (AK), USA"  : "BET",
    "Bhopal, India"  : "BHO",
    "Bhubaneswar, India"  : "BBI",
    "Biarritz, France"  : "BIQ",
    "Bilbao, Spain"  : "BIO",
    "Billings (MT), USA"  : "BIL",
    "Billund, Denmark"  : "BLL",
    "Bintulu, Malaysia"  : "BTU",
    "Biraro, Central African Republic"  : "IRO",
    "Birmingham - Birmingham International Airport, United Kingdom"  : "BHX",
    "Birmingham (AL), USA"  : "BHM",
    "Bishkek - Manas International Airport, Kyrgyzstan"  : "FRU",
    "Bismarck (ND) - Bismarck Municipal Airport, USA"  : "BIS",
    "Bissau - Osvaldo Vieiro International Airport, Guinea-Bissau"  : "BXO",
    "Blackpool, United Kingdom"  : "BLK",
    "Blackwater, Australia"  : "BLT",
    "Blantyre (Mandala) - Chileka International Airport, Malawi"  : "BLZ",
    "Blenheim, New Zealand"  : "BHE",
    "Bloemfontein - Bloemfontein Airport, South Africa"  : "BFN",
    "Bloomington (IL), USA"  : "BMI",
    "Bloomington (IN), USA"  : "BMG",
    "Bluefield (WV), USA"  : "BLF",
    "Boa Vista, Brazil"  : "BVB",
    "Bobo/Dioulasso, Burkina Faso"  : "BOY",
    "Bodo, Norway"  : "BOO",
    "Bodrum - Milas Airport, Turkey"  : "BJV",
    "Bogota - El Nuevo Dorado International Airport, Colombia"  : "BOG",
    "Boise (ID) - Boise Air Terminal, USA"  : "BOI",
    "Bologna, Italy"  : "BLQ",
    "Bombay (Mumbai) - Chhatrapati Shivaji International, India"  : "BOM",
    "Bonaire, Netherlands Antilles"  : "BON",
    "Bonaventure, PQ, Canada"  : "YVB",
    "Bora Bora, French Polynesia"  : "BOB",
    "Bordeaux - Bordeaux Airport, France"  : "BOD",
    "Borrego Springs (CA), USA"  : "BXS",
    "Boston (MA) - General Edward Lawrence Logan, USA"  : "BOS",
    "Bouake, Cote d'Ivoire"  : "BYK",
    "Bourgas/Burgas, Bulgaria"  : "BOJ",
    "Bournemouth, United Kingdom"  : "BOH",
    "Bowen, Australia"  : "ZBO",
    "Bozeman (MT), USA"  : "BZN",
    "Bradford/Warren (PA) /Olean (NY), USA"  : "BFD",
    "Brainerd (MN), USA"  : "BRD",
    "Brampton Island, Australia"  : "BMP",
    "Brasilia - President Juscelino Kubitschek International, Brazil"  : "BSB",
    "Bratislava - M. R. Štefánik Airport, Slovakia"  : "BTS",
    "Brazzaville - Maya-Maya Airport, Congo (ROC)"  : "BZV",
    "Bremen - Bremen Airport (Flughafen Bremen), Germany"  : "BRE",
    "Brescia, Montichiari, Italy"  : "VBS",
    "Brest, France"  : "BES",
    "Bria, Central African Republic"  : "BIV",
    "Bridgeport (CT), USA"  : "BDR",
    "Bridgetown - Grantley Adams International, Barbados"  : "BGI",
    "Brindisi, Italy"  : "BDS",
    "Brisbane, Australia"  : "BNE",
    "Bristol, United Kingdom"  : "BRS",
    "Broennoeysund, Norway"  : "BNN",
    "Broken Hill, Australia"  : "BHQ",
    "Brookings (SD), USA"  : "BKX",
    "Broome, Australia"  : "BME",
    "Brunswick (GA), USA"  : "BQK",
    "Brussels - Brussels Airport, Belgium"  : "BRU",
    "Bucaramanga, Colombia"  : "BGA",
    "Bucharest, Romania"  : "BUH",
    "Bucharest - Henri Coandă International Airport, Romania"  : "OTP",
    "Budapest - Budapest Ferihegy International Airport, Hungary"  : "BUD",
    "Buenos Aires, Argentina"  : "BUE",
    "Buenos Aires, Ezeiza International Airport, Argentina"  : "EZE",
    "Buenos Aires, Jorge Newbery, Argentina"  : "AEP",
    "Buffalo Range, Zimbabwe"  : "BFO",
    "Buffalo/Niagara Falls (NY), USA"  : "BUF",
    "Bujumbura - Bujumbura International Airport, Burundi"  : "BJM",
    "Bulawayo, Zimbabwe"  : "BUQ",
    "Bullhead City (NV), USA"  : "BHC",
    "Bundaberg, Australia"  : "BDB",
    "Burbank (CA), USA"  : "BUR",
    "Burlington IA, USA"  : "BRL",
    "Burlington (VT), USA"  : "BTV",
    "Burnie (Wynyard), Australia"  : "BWT",
    "Butte (MT), USA"  : "BTM",
    "Cabinda, Angola"  : "CAB",
    "Cagliari, Italy"  : "CAG",
    "Cairns, Australia"  : "CNS",
    "Cairo - Cairo International Airport, Egypt"  : "CAI",
    "Calama - El Loa, Chile"  : "CJC",
    "Calcutta (Kolkata) - Netaji Subhas Chandra, India"  : "CCU",
    "Calgary - Calgary International Airport, Canada"  : "YYC",
    "Cali, Colombia"  : "CLO",
    "Calicut, India"  : "CCJ",
    "Calvi, France"  : "CLY",
    "Cambridge Bay, Canada"  : "YCB",
    "Cambrigde, United Kingdom"  : "CBG",
    "Campbeltown, United Kingdom"  : "CAL",
    "Campo Grande, Brazil"  : "CGR",
    "Canberra - Canberra Airport, Australia"  : "CBR",
    "Cancun, Mexico"  : "CUN",
    "Cannes – Mandelieu Airport, France"  : "CEQ",
    "Canouan (island) - Canouan Airport, Saint Vincent & the Grenadines"  : "CIW",
    "Cape Town - Cape Town International Airport, South Africa"  : "CPT",
    "Caracas - Simón Bolívar International Airport, Venezuela"  : "CCS",
    "Cardiff - Cardiff Airport, United Kingdom"  : "CWL",
    "Carlsbad (CA), USA"  : "CLD",
    "Carnarvon, Australia"  : "CVQ",
    "Carnot, Central African Republic"  : "CRF",
    "Carson City (NV), USA"  : "CSN",
    "Casablanca, Morocco"  : "CAS",
    "Casablanca, Mohamed V, Morocco"  : "CMN",
    "Casa de Campo - La Romana International Airport, Dominican Republic"  : "LRM",
    "Casino, Australia"  : "CSI",
    "Casper (WY), USA"  : "CPR",
    "Castaway, Fiji"  : "CST",
    "Cartagena - Rafael Núñez International Airport, Colombia"  : "CTG",
    "Castries - George F. L. Charles Airport, Saint Lucia"  : "SLU",
    "Catania, Italy"  : "CTA",
    "Cayenne - Cayenne-Rochambeau Airport, French Guiana"  : "CAY",
    "Cottbus - Cottbus-Drewitz Airport, Germany"  : "CBU",
    "Cebu City - Mactan-Cebu International, Philippines"  : "CEB",
    "Cedar City (UT), USA"  : "CDC",
    "Cedar Rapids IA, USA"  : "CID",
    "Ceduna, Australia"  : "CED",
    "Cessnock, Australia"  : "CES",
    "Chabarovsk (Khabarovsk), Russia"  : "KHV",
    "Chambery, France"  : "CMF",
    "Champaign (IL), USA"  : "CMI",
    "Chandigarh - Chandigarh International Airport, India"  : "IXC",
    "Changchun, Jilin, PR China"  : "CGQ",
    "Chania, Greece"  : "CHQ",
    "Port Macquarie, Australia"  : "PQQ",
    "Port Menier, PQ, Canada"  : "YPN",
    "Port Moresby - Jackson Field, Papua New Guinea"  : "POM",
    "Porto, Portugal"  : "OPO",
    "Porto Alegre - Salgado Filho International Airport, Brazil"  : "POA",
    "Port of Spain - Piarco International, Trinidad and Tobago"  : "POS",
    "Port Said, Egypt"  : "PSD",
    "Porto Santo, Portugal"  : "PXO",
    "Porto Velho, Brazil"  : "PVH",
    "Port Vila, Vanuatu"  : "VLI",
    "Poughkeepsie (NY), USA"  : "POU",
    "Poznan, Lawica, Poland"  : "POZ",
    "Prague - Václav Havel Airport (formerly Ruzyne), Czech Republic"  : "PRG",
    "Praia - Nelson Mandela International Airport, Cape Verde"  : "RAI",
    "Presque Island (ME), USA"  : "PQI",
    "Pretoria - Wonderboom Apt., South Africa"  : "PRY",
    "Preveza/Lefkas, Greece"  : "PVK",
    "Prince George, Canada"  : "YXS",
    "Prince Rupert/Digby Island, Canada"  : "YPR",
    "Pristina, Serbia"  : "PRN",
    "Prosperpine, Australia"  : "PPP",
    "Providence (RI), USA"  : "PVD",
    "Prudhoe Bay (AK), USA"  : "SCC",
    "Puebla, Mexico"  : "PBC",
    "Pueblo (CO), USA"  : "PUB",
    "Puerto Escondido, Mexico"  : "PXM",
    "Puerto Ordaz, Venezuela"  : "PZO",
    "Puerto Plata, Dominican Republic"  : "POP",
    "Puerto Vallarta, Mexico"  : "PVR",
    "Pukatawagan, Canada"  : "XPK",
    "Pula, Croatia (Hrvatska)"  : "PUY",
    "Pullman (WA), USA"  : "PUW",

    "Simferopol, Ukraine"  : "SIP",
    "Sindhri, Pakistan"  : "MPD",
    "Singapore - Changi, Singapore"  : "SIN",
    "Singapore - Paya Lebar, Singapore"  : "QPG",
    "Singapore - Seletar, Singapore"  : "XSP",

    "Zurich (Zürich) - Kloten, Switzerland"  : "ZRH"
    };
   